version: "3.8"

services:
    websocket_app:
        container_name: webSocket_server
        image: node:lts-alpine
        working_dir: /app
        ports:
            - 8081:8081
        volumes:
            - .:/app
        entrypoint: [ "/app/entrypoint.sh" ]
        command: [ "node" ]
        # entrypoint: ['npm', '']
        tty: true
        env_file:
            - ./.env
        # command: nodemon app.js
